<div id="task1">
    <h3>Task1</h3>
    <?php echo $this->getData("tree"); ?>
</div>
<div id="task2">
    <h3>Task2</h3>
    <div id="imgBlock">
        <img onClick="changePicture()" width="200" height="200" src="<?php echo Init::getBaseDir("media" . DS . "images" . DS . "41308-1600x1200.jpg"); ?>" />
        <img onClick="changePicture()" width="200" height="200" src="<?php echo Init::getBaseDir("media" . DS . "images" . DS . "6976-1600x1200.jpg"); ?>" />
    </div>
</div>
